---
# tasks file for ansible-role-vault
- name: Install system requirements
  ansible.builtin.package:
    name: '{{ vault_required_system_packages }}'

- name: Add Hashicorp repository
  ansible.builtin.yum_repository:
    name: Hashicorp
    description: Hashicorp
    enabled: true
    gpgcheck: true
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: Install vault
  ansible.builtin.package:
    name: '{{ vault_package }}'

- name: Insert vault license file
  ansible.builtin.copy:
    src: '{{ vault_license_file_source }}'
    dest: '{{ vault_enterprise_license_location }}'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '0640'
  when:
    - vault_license_file_source | d(False)
    - vault_enterprise_license_location | d(False)

- name: Insert vault config template
  ansible.builtin.template:
    src: 'vault.hcl.j2'
    dest: '/etc/vault.d/vault.hcl'
    owner: '{{ vault_user }}'
    group: '{{ vault_group }}'
    mode: '0640'
